pipeline {
    agent any

    tools {
        nodejs 'node20'
    }

    environment {
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials'
        DOCKER_IMAGE_FRONTEND = 'bahabah/glunovita-frontend'
        DOCKER_TAG = "v${env.BUILD_ID}"
    }

    stages {
        stage('1. Checkout') {
            steps {
                checkout scm
            }
        }

        stage('2. Installation') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                }
            }
        }

        stage('3. Lint (Analyse Statique)') {
            steps {
                dir('frontend') {
                    sh 'npm run lint'
                }
            }
        }

        stage('4. Unit Tests') {
            steps {
                dir('frontend') {
                    sh 'npm test -- --passWithNoTests || echo "Aucun script de test configuré"'
                }
            }
        }

        stage('5. Build') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('6. SonarQube') {
            environment {
                SCANNER_HOME = tool 'SonarQubeScanner'
            }
            steps {
                sh "${SCANNER_HOME}/bin/sonar-scanner \
                    -Dsonar.host.url=http://172.17.0.2:9000 \
                    -Dsonar.login=admin \
                    -Dsonar.password=admine \
                    -Dsonar.projectKey=glunovita-frontend \
                    -Dsonar.sources=frontend"
            }
        }

        stage('7. Trivy (Sécurité)') {
            steps {
                dir('frontend') {
                    // Utilise l'image Docker officielle de Trivy pour scanner le dossier sans avoir besoin de l'installer
                    sh 'docker run --rm -v ${WORKSPACE}/frontend:/workspace aquasec/trivy:latest fs --severity HIGH,CRITICAL /workspace'
                }
            }
        }

        stage('8. Docker Build') {
            steps {
                dir('frontend') {
                    sh "docker build -t ${DOCKER_IMAGE_FRONTEND}:${DOCKER_TAG} -t ${DOCKER_IMAGE_FRONTEND}:latest ."
                }
            }
        }

        stage('9. Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIALS_ID, passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push ${DOCKER_IMAGE_FRONTEND}:${DOCKER_TAG}"
                    sh "docker push ${DOCKER_IMAGE_FRONTEND}:latest"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo "✅ Pipeline Frontend terminé avec succès !"
        }
        failure {
            echo "❌ Le pipeline Frontend a échoué."
        }
    }
}
